### ISSUE TITLE
Mailinglist is down

### ISSUE THREAD

**Issue by untitaker** [pocoo/metaflask#60]
http://librelist.com/browser/flask/

Have the same issues as https://github.com/zedshaw/librelist/issues/7

**Comment by lepture** [comment]
There is a Django-india on the Python mail list.

**Comment by untitaker** [comment]
Can I create a ML through the link @jamesonjlee posted? Or should I request one from some person?

**Comment by untitaker** [comment]
Apparently not.

**Comment by untitaker** [comment]
Found the info: https://www.python.org/community/lists/

Will ask Armin first.

**Comment by untitaker** [comment]
Sent a mail to the official postmaster-address and recieved an automatic reply by charite.de, see https://gist.github.com/untitaker/a9ba9e4a1608d16ff0d0. @DasIch IIRC you're affiliated with that Charite?

**Comment by patrickbenkoetter** [comment]
I've just created a mailing list for flask at python.org: https://mail.python.org/mailman/listinfo/flask.

**Comment by untitaker** [comment]
Thanks!

**Comment by Juanlu001** [comment]
:tada: :tada: :tada:

**Comment by untitaker** [comment]
I think in this case we should perhaps decide what the mailing list should provide.

I personally would like to keep support discussions at StackOverflow as much as possible, and only make users post to the list for longer discussions. Instead I'd like the ML to be more a place for official announcements and organizational matters. Technical discussions should largely stay at GitHub, too.

**Comment by jeffwidman** [comment]
Many projects have two mailing lists: 'Announce' + the discussion list.

I'd vote for having both. I know there are times I've wanted to ask others how they've solved an architecture/design question that SO probably isn't quite the right format for, and it's not a bug or technical issue with Flask so Github issues aren't appropriate either. I also appreciated the quality of questions/responses on the Flask list in general.  I learned of a number of different techniques/features by reading the list that likely would have been lost in the noise if I'd just followed the SO flask tag. 

But there's also a number of projects that I only subscribe to the announce list so I can stay on top of releases & security alerts, but otherwise don't want to get the extra list chatter. I'd expect the Flask announce list would have <10 emails a year, more likely <5.

Also, FWIW, Librelist is completely borked for me. A few months ago it just stopped sending me messages, and doesn't accept my messages either... nothing I do seems to fix it, nor do I get any feedback of bounces/spam notifications. So I'd love to see us migrate to anything at all other than Librelist.

**Comment by anddam** [comment]
I've been having the same issues for months. I conracted librelist.com and in one occasion I was able to get a reply, they "fixed" my account and I got messages for a brief while, then it went blank again.

I'm conflicted about using separate resources (mailing list, StackOverflow, github) as it makes harder to access the information, having to use different programs to access different locations. A single central point of access to information has an advantage for me.

OTOH mailing list aren't ideal for keeping support requests and their answers, frequent questions tend to repeat over and over in time since newcomers won't { be able | bother } to look if their question is already in the archive.
StackOverflow in that matter is a bit better as it provides a feedback of what's more popular and that pops out in search (of course this still assumes an user well-behaves and actually does search). Also it has visual niceties that don't harm.

As personal taste I'd go with just the mailing list(s), given that flask has already good documentation and snippets archive that can be referenced to/augmented.

I joined the list @patrickbenkoetter created but it's still empty. I have no access to librelist so I don't know if it's still alive and if this topic is being discussed.

**Comment by jeffwidman** [comment]
For anyone who stumbles across this in the future, we've now migrated the mailing list to https://mail.python.org/mailman/listinfo/flask/

This issue can probably be closed once https://github.com/mitsuhiko/flask-website/pull/20 is accepted. It updates the mailing list info on the Flask website to reflect the change.

Associated discussion on the old librelist mailing list: http://librelist.com/browser//flask/2015/7/14/switch-mailing-list-software-away-from-librelist/

**Comment by untitaker** [comment]
Finally, done!

I'm currently messing around with the mailing list settings. I've added @rduplain @mitsuhiko @DasIch as admins and @jeffwidman as moderator. Leave a comment on this (closed) issue if you think you should be one too.

**Comment by untitaker** [comment]
I've now also added @RonnyPfannschmidt.

**Comment by untitaker** [comment]
I just noticed that mailman has one single moderation password and one single admin password.

Contact me in private to get either of those.
